### ISSUE TITLE
Why react and react-dom are not in peerDependency?

### ISSUE THREAD

**Issue by GianDigia** [kako0507/react-onclickoutside-decorator#7]
I refer to these lines in package.json

https://github.com/kako0507/react-onclickoutside-decorator/blob/2271f5dbfc81ad28708f335fc3ea877969fab78b/package.json#L30-L31

I'm not an expert but as far as I know they both should be in "peerDependencies" and "devDependencies".

Can you please consider changing that behaviour? @kako0507

**Comment by kako0507** [comment]
@GianDigia  Thanks for your helping :)
